# Generated by Django 4.2.7 on 2025-11-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('appointment_confirmation', 'Appointment Confirmation'), ('appointment_reminder', 'Appointment Reminder'), ('appointment_cancelled', 'Appointment Cancelled'), ('doctor_message', 'Doctor Message'), ('prescription_update', 'Prescription Update'), ('system', 'System Notification')], default='system', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
