# Generated by Django 4.2.26 on 2025-12-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/photos/'),
        ),
    ]
